import { Inter } from "next/font/google";
// import "./globals.css";
import "./home.css";
import "./index.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Links Saver",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
